# Site settings
#baseurl = "https://yourbrowsbyrachel.com/"
baseurl = ""
languageCode = "en-us"
title = "Your Brows by Rachel"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-91368406-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Rachel Fayko"
  description = "Brow Sculptor"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Your Brows by Rachel"
    # Optional logo as brand stored in img/
    #logo = "ybr_logo.jpg"
    about = "About Me"
    hours = "Hours"
    services = "Services"
    directions = "Directions"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Specializing in your brows since 2006"
    #subtitle = "specializing in your brows since 2006"
    buttonText = "Book Your Appt. Now"

  # About section
  [params.about]
    enable = true
    title = "About Me"
    subtitle = "dedicated to your brow perfection for some time now..."
    img = "me.jpg"
    description = "I have specialized in brow scuplting since 2006.  I enjoy working with my clients one on one to perfectly match their brows with their unique face type.  It is this personal connection that leaves my clients feeling appreciated and looking their best each and every time we are together.  I look forward to sculpting your brows!"

  # Hours section
  [params.hours]
    enable = true
    title = "Hours"
    subtitle = "when you can get your brows done..."

    [[params.hours.row]]

    [[params.hours.row.list]]
      title = "Wednesday"
      description = "10am to 7pm"

    [[params.hours.row.list]]
      title = "Thursday"
      description = "10am to 7pm"

    [[params.hours.row.list]]
      title = "Friday"
      description = "9am to 6pm"

    [[params.hours.row.list]]
      title = "3rd Saturday OTM"
      description = "9am to 4pm"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = "conscientious waxing for men and women neck up."

    [[params.services.row]]

    [[params.services.row.list]]
      #icon = "fa-shopping-cart"
      title = "Brows"
      description = "Waxing brows - $22"
      #url = "#"

    [[params.services.row.list]]
      #icon = "fa-laptop"
      title = "Lip"
      description = "Waxing upper lip - $10"
      #url = "#"

    [[params.services.row.list]]
      #icon = "fa-lock"
      title = "Chin"
      description = "Waxing chin - $8"
      #url = "#"

    [[params.services.row.list]]
      #icon = "fa-lock"
      title = "Face"
      description = "Waxing side burn area - $15"
      #url = "#"

  # directions section
  [params.directions]
    enable = true
    title = "Directions to the Studio"
    subtitle = "277 Alexander Street suite 206, Rochester, NY 14607<br>Phone: 585-376-2626"
    imgmap = "imgmap.jpg"
    imgbldg = "bldg.jpg"
    description = "Your Brows by Rachel is located in Kicksalon on the 2nd floor of the Medical Arts Building on the corner of Gardiner Park and Alexander St. in the East End Neighborhood across the street from the Ox and Stone restaurant.  If you are familar with where Park Ave butts into Alexander St. You are in the right spot.  Use the double doors on Gardiner Park and enter the lovely lobby where you'll take the elevator to the 2nd floor.  Kicksalon is immediately off the elevator to your left. Click the map for google map directions -->"
    url = "https://goo.gl/maps/bk8LJTNXcXL2"

  # Contact 
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Phone: (585) 376 - 2626"
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "yourbrowsbyrachel@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Thank you for contacting us. We will reply shortly..."
    error = "Message could not be sent. Please contact us at yourbrowsbyrachel@gmail.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    #[params.contact.form.phone]
    # text = "Your Phone *"
    #  warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
         name = "website submission"
      #  value = "example.com"
      #  name = "page"

  # Footer section
  [params.footer]
    enable = false
    #copyright = "copyright 2017."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"

    [[params.footer.quicklinks]]
      #text = "Privacy Policy"
      #link = "#"

    [[params.footer.quicklinks]]
      #text = "Terms of Use"
      #link = "#"
